server:
  port: 8081

spring:
  application:
    name: logical-back
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/logical_back?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: miaomiao_user    # 使用root用户
    password: miaomiao123 # 请修改为您的MySQL root密码
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 日志配置
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.example.logicalback: debug 